# Generated by Django 3.2.5 on 2021-07-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group2Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Optional field to add an organization-specific code in addition to the name', max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Group Kind',
                'verbose_name_plural': 'Group Kinds',
            },
        ),
        migrations.CreateModel(
            name='Group2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Optional field to add an organization-specific code in addition to the name', max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this if the Group2 is not active any more')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('group', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups2.group2kind', verbose_name='Kind')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
